include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    public_member_api_docs: ignore
    lines_longer_than_80_chars: ignore

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    one_member_abstracts: false
    avoid_positional_boolean_parameters: false
    sort_pub_dependencies: false
    eol_at_end_of_file: false
