// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgDqTYxa1OHph-cX1ajbSiyvb7VS_zSf4',
    appId: '1:86164499506:web:d29b4bf2e6ccf034e7e02b',
    messagingSenderId: '86164499506',
    projectId: 'asrostore-9a929',
    authDomain: 'asrostore-9a929.firebaseapp.com',
    storageBucket: 'asrostore-9a929.firebasestorage.app',
    measurementId: 'G-SFJEGZCZ58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeG2UkO0i-pGWpREq78oCd_rwKJdWMeyw',
    appId: '1:86164499506:android:4c83d6139d379c41e7e02b',
    messagingSenderId: '86164499506',
    projectId: 'asrostore-9a929',
    storageBucket: 'asrostore-9a929.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwMe7BY0-I3_WbZsMvQaZ_zG5Qf9TUQ_o',
    appId: '1:86164499506:ios:2d8c15f2f50217e9e7e02b',
    messagingSenderId: '86164499506',
    projectId: 'asrostore-9a929',
    storageBucket: 'asrostore-9a929.firebasestorage.app',
    iosBundleId: 'com.example.asrooStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwMe7BY0-I3_WbZsMvQaZ_zG5Qf9TUQ_o',
    appId: '1:86164499506:ios:2d8c15f2f50217e9e7e02b',
    messagingSenderId: '86164499506',
    projectId: 'asrostore-9a929',
    storageBucket: 'asrostore-9a929.firebasestorage.app',
    iosBundleId: 'com.example.asrooStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgDqTYxa1OHph-cX1ajbSiyvb7VS_zSf4',
    appId: '1:86164499506:web:3eff6761266a0ecfe7e02b',
    messagingSenderId: '86164499506',
    projectId: 'asrostore-9a929',
    authDomain: 'asrostore-9a929.firebaseapp.com',
    storageBucket: 'asrostore-9a929.firebasestorage.app',
    measurementId: 'G-SY53D9JFE6',
  );
}
